### ISSUE TITLE
Preview link will cause confusion with original link.

### ISSUE THREAD

**Issue by two-pack** [taqueci/redmine_wysiwyg_editor#1]
This plugin places **Preview** link under wysiwyg edit place.
But Redmine has already Preview link near confirming button, like **Create** in issue page.
I think the link will cause confusion, so it's better to remove it.

**Comment by taqueci** [comment]
I don't remove the new preview link because some users like it.
Redundant links may be confusing, so I will consider removing the original one.

**Comment by taqueci** [comment]
In Redmine 4.0.0, preview link has been removed by:
[27758 Adds preview option to the wiki toolbar](http://www.redmine.org/issues/27758)

So I will not remove the original preview link by this plugin.

If you want to remove it, please use [view customize plugin](https://github.com/onozaty/redmine-view-customize) with:
```js
$(function() {
    $('a[accesskey=r]').hide();
});
```

**Comment by two-pack** [comment]
Thanks information and workaround :grinning:
I agree your opinion.
