### ISSUE TITLE
Cannot read property 'menu' of undefined

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#10]
Open new issue creation page
redmine.domain/projects/project_id/issues/new#

Result:
Infinity "Loading"

![screenshot at 11-31-46](https://user-images.githubusercontent.com/1729590/45412547-931c3000-b67f-11e8-967a-5c506aa00c99.png)

**Comment by taqueci** [comment]
I have reproduced the issue in my environment.
It is caused by enabling default template of issue template plugin.

I will investigate the root cause.

**Comment by taqueci** [comment]
Hi @chevi 

I have fixed the issue.
Please try the latest commit in develop branch.

**Comment by chevi** [comment]
Hi @taqueci 

Tested. Issue can be closed. Thanks!
