### ISSUE TITLE
Markdown mode -> Italic doesn't work

### ISSUE THREAD

**Issue by mertlexo** [taqueci/redmine_wysiwyg_editor#100]
Hey there,

thank you very much for this great editor. 

We have a small problem with italic formatting in combination with Markdown. Italic formatting inserts underscores before and after the word, but in Redmine Markdown this means that the word is underlined. Therefore, italic formatting only works in the editor - in the preview or after saving, the word is underlined. 

![image](https://user-images.githubusercontent.com/32308357/88024272-b98c3b80-cb32-11ea-8148-bf5afa3d9713.png)
![image](https://user-images.githubusercontent.com/32308357/88024302-c446d080-cb32-11ea-8617-fc427a97aeae.png)
![image](https://user-images.githubusercontent.com/32308357/88024333-cdd03880-cb32-11ea-8132-9617019ecd65.png)

**Comment by taqueci** [comment]
Thank you for your reporting.
I will investigate.

**Comment by taqueci** [comment]
| Style          | Markdown             | Visual editor                                                       |
|---|---|---|
| Bold           | `**Bold**`           | `<strong>Bold</strong>`                                              |
| Italic         | `*Italic*`           | `<em>Italic</em>`                                                    |
| Underline      | `_Underline_`        | `<span style="text-decoration: underline;">Underlilne</span>`        |
| Strike through | `~~Strike through~~` | `<span style="text-decoration: line-through;">Strike through</span>` |

**Comment by taqueci** [comment]
The issue has been fixed.
