### ISSUE TITLE
Failed to load plugin mention with TinyMCE 4.9.11

### ISSUE THREAD

**Issue by nanego** [taqueci/redmine_wysiwyg_editor#102]
Hello @taqueci 
I am getting this error with the last version of the plugin, when loading a page which use a wysiwyg editor.

    Failed to load plugin: mention from url /plugin_assets/redmine_wysiwyg_editor/javascripts/tinymce/plugins/mention/plugin.min.js`

It seems to come from the upgrade to TinyMCE 4.9.11, which has removed this JS file. 
Thank you for your help.

    Environment:
      Redmine version                4.1.1.stable
      Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
      Rails version                  5.2.4.2

**Comment by taqueci** [comment]
Thank you for your reporting.
The issue has been fixed.
