### ISSUE TITLE
I do not know exactly whether it is a Redmine problem or a textile problem.

### ISSUE THREAD

**Issue by AlexB72** [taqueci/redmine_wysiwyg_editor#104]
```
# numbered list item 1
# numbered list item 2
* bulleted list first item
* bulleted list second item
 text numbered list item 2
# numbered list item 3
```

```
<ol>
<li># numbered list item 1</li>
<li># numbered list item 2
<ul>
<li>* bulleted list first item</li>
<li>* bulleted list second item</li>
</ul> 
text numbered list item 2</li>
<li># numbered list item 3</li>
</ol>
```

The basic structure is clear to me, only the details are missing. I want the line "text numbered list item 2" to be on the "numbered list item 2" level and not count towards "bulleted list second item".
To be honest, I don't care where the error comes from. Do you have any ideas how I can solve this problem? Redmine Wiki is unfortunately very destructive when it comes to html and css.
"Text numbered list item 2" are warning notices or further explanations on the issues in "numbered list item 2". I certainly don't want it as a new one
See "numbered list item 3". This kind of nested lists is quite common and I get annoyed every day about the incorrect display.
Many thanks for your help.
I apologize for my bad English, I'm mainly at home in German.

**Comment by taqueci** [comment]
Hi @AlexB72 

Please write:
```
# numbered list item 1
# numbered list item 2
** bulleted list first item
** bulleted list second item
 text numbered list item 2
# numbered list item 3
```

I don't know how to solve "text numbered list item 2"...
