### ISSUE TITLE
Allow resizing of images

### ISSUE THREAD

**Issue by varenius** [taqueci/redmine_wysiwyg_editor#106]
It would be very useful to allow resizing of images included in tickets and wiki pages. Is there any plan to include this feature in the editor?

**Comment by taqueci** [comment]
Hi @varenius 

Resizing image is available by using Textile or Markdown with HTML tags allowance.

I guess you use Markdown.
Please enable HTML tags.

https://www.redmine.org/boards/2/topics/56096#message-57052

**Comment by varenius** [comment]
Thank you for the link, I didn't know about this possibility. 

Indeed, I use markdown. I thought there was a simpler way than writing pure HTML, but then I guess there isn't one. (I think some other WYSIWYG editors (e.g. CKEditor) allow re-sizing of images within a dialog box).

But the HTML-way works for now.
