### ISSUE TITLE
Refactor testing setup

### ISSUE THREAD

**Issue by martincizek** [taqueci/redmine_wysiwyg_editor#107]
The current testing setup deserves a few improvements to make development easier and more sustainable:
* Remove / externalize auxiliary code in unit tests. Currently there is just one test file, so it is not a big deal now, but more test files may / should come.
* Minimize the amount of NodeJS / browser code branches in non-auxiliary code.
* Provide support for headless testing to facilitate both writing test code and its reliability. With recent JSDom and smart setup, there is no need for headless browser to achieve this.
* Match jQuery version current Redmine version.

Creating this issue for eventual discussion. We've already made this for making `redmine_wysiwyg_editor` improvements. A PR will be submitted in a moment.

P.S. We like this plugin's momentum and we'd like to cooperate on it - especially in the format conversion area.

**Comment by taqueci** [comment]
PR #108 has been merged.
Thank you for the fantastic work!
