### ISSUE TITLE
Feature request: improve Wiki link dialogue; omit spaces around monospace 

### ISSUE THREAD

**Issue by albrechtd** [taqueci/redmine_wysiwyg_editor#112]
(Sorry, accidentally hit the return key…)

I would like to propose two minor (!) improvements…

First, it seems that the list of projects in the *Insert Wiki Link* dialogue is unsorted (is it?).  As we have many projects in Redmine, the dialogue is somewhat confusing for the user, and finding the right item for a cross-project link is difficult.  Would is be possible to (case-insensitively) sort the project list in the combo by by name?

Furthermore, the Wiki page titles always include “_” chars instead of spaces which looks a little ugly.  Would it be possible to replace them by spaces, both in the combo box and in the Textile output?

Second, I noticed that the Visual Editor sometimes adds spaces around `@…@` blocks, e.g. enter in Textile mode
```
see (@code@)... some @uid@-specific stuff
```
switch to the Visual Editor, enter something, and switch back to textile.  Now the line above reads
```
see ( @code@ )... some @uid@ -specific stuff
```
I *think* (not sure, though) that the extra space is required iff the adjacent char is a ASCII letter or a digit.  As alternative, the space could also be replaced by a `<notextile></notextile>` sequence.

**Comment by albrechtd** [comment]
BTW, a similar effect happens with a ticket link like
```
(see ticket #1234)
```
which is converted to
```
(see ticket #1234 )
```

**Comment by taqueci** [comment]
Hi @albrechtd 

I have fixed:
- Order of projects
- Wiki page title

As to spaces around code block, I have created the new issue #113.
I need some time to consider.
