### ISSUE TITLE
wysiwig editor for custom fields?

### ISSUE THREAD

**Issue by dpalic** [taqueci/redmine_wysiwyg_editor#119]
we have a text area custom field and use there the Wiki tables there for displaying tables in a custom field.

Is there an option to use the wysiwig editor for custom fields?

**Comment by taqueci** [comment]
Hi @dpalic 

Please enable `Full width layout` in custom field setting.

**Comment by lcasanova78** [comment]
In Redmine 3.3 there is no Full width layout in custom field setting option, is there any way to use the wysiwyg editor in a custom field?
