### ISSUE TITLE
Pasting image does not work

### ISSUE THREAD

**Issue by taqueci** [taqueci/redmine_wysiwyg_editor#12]
Image pasting functionality does not work in the environment below:

**Redmine version**
- Redmine 3.3.0.stable

**Installed plugins**
- Time Logger
- Redmine Work Time plugin
- Redmine Theme Changer plugin
- Redmine Issue Templates plugin
- Redmine Embedded Video
- Clipboard image paste
- A common libraries
- Extra Queries plugin

**Browser version**
- Chrome 68 / Firefox 62 (64-bit) / Vivaldi 1.15.1147.64 (64-bit)

![](https://user-images.githubusercontent.com/1729590/45412163-ad094300-b67e-11e8-9a7f-480d34672569.png)

_Originally posted by @chevi in https://github.com/taqueci/redmine_wysiwyg_editor/issues/11#issuecomment-421293053_

**Comment by chevi** [comment]
@taqueci I'm happy to say that image pasting works with 0.2.5 version
Thanks a mil
Issue can be closed

**Comment by taqueci** [comment]
That's good news :smiley:
