### ISSUE TITLE
Preserve HTML-Content

### ISSUE THREAD

**Issue by mmundi72** [taqueci/redmine_wysiwyg_editor#122]
When adding a < br > it is being saved properly and everything looks good. Editing the page again the < br > is visible in the Markdown view but it is being removed as soon as the page is beeing edited with visual editor.

Here is an example:

Create new wiki page and add a table using visual edtior:
![image](https://user-images.githubusercontent.com/7224922/115664046-a74d6100-a341-11eb-9507-5d5de4730628.png)

Save the page. Result:
![image](https://user-images.githubusercontent.com/7224922/115663814-59385d80-a341-11eb-8fb4-0c9af49f4fca.png)

Edit the page and switch to Markdown. < br > is visible:
![image](https://user-images.githubusercontent.com/7224922/115664108-b59b7d00-a341-11eb-8c11-2458420f8115.png)

Switch to visual editor. Click into the cell with the < br >. Do not make any changes to the content. Switch back zu Markdown. < br > is now removed.
![image](https://user-images.githubusercontent.com/7224922/115664171-ca781080-a341-11eb-8d6e-1a1537440974.png)

**Comment by mmundi72** [comment]
We are using markdown as this also provides the possibility to use some HTML. The solution seems to work with textile but not with markdown. I still think that manually entered HTML should be maintained.

**Comment by mmundi72** [comment]
Any news concerning this issue? It's now more than 2 years old. Users in our company are asking when this is going to be fixed.
Thanks for your work.

**Comment by taqueci** [comment]
Hi @mmundi72

Version 0.30.0 has just been released.
`<br>` in Markdown table is reserved.
Please confirm.

**Comment by mmundi72** [comment]
Yes, that looks great. Thank you for your work!
