### ISSUE TITLE
Editor for notes?

### ISSUE THREAD

**Issue by DolezalDavid** [taqueci/redmine_wysiwyg_editor#123]
Hi @taqueci,
is it possible to enable this usefull plugin for isseue's notes and wiki's comments? 

Thank you for you work. 

With best regards

David

**Comment by taqueci** [comment]
Hi @DolezalDavid 

This plugin is available for issue's notes and is not available for wiki's comments.
Do you mean visual editor does not appear when editing an issue?

**Comment by DolezalDavid** [comment]
hmm, interesting...

By me isn't the same as on your pic
![obrazek](https://user-images.githubusercontent.com/52913270/116407424-0d4e5280-a832-11eb-9f3b-bb9b6616aa0e.png)

**Comment by DolezalDavid** [comment]
Here is my setup
![obrazek](https://user-images.githubusercontent.com/52913270/116407734-5dc5b000-a832-11eb-8f9a-8a072013df96.png)

**Comment by taqueci** [comment]
_Note to self:_
The issue is not reproduced.
```
Environment:
  Redmine version                4.2.0.stable
  Ruby version                   2.7.3-p183 (2021-04-05) [x86_64-linux-musl]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Mercurial                      5.5.2
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_custom_workflows       1.0.4
  redmine_home_page_redirector   1.0.0
  redmine_lightbox2              0.5.1
  redmine_local_avatars          1.0.5.2.0
  redmine_wysiwyg_editor         0.21.0
```

**Comment by nanego** [comment]
Same problem here after updating our main application.
It seems we have to activate the "editor visual" module for ALL our projects. It's a bit fastidious as we have hundreds of them.

**Comment by taqueci** [comment]
Hi @DolezalDavid 

Since 0.21.0, the visual editor is disabled as default.
Please enable "Visual editor" in each project module settings if it is disabled.

**Comment by DolezalDavid** [comment]
@nanego Great. I used your fix, and it looks good. 

Last quick question: "How to set Visual Editor for all users as default editor?" :-) Awsome work guys! 

Thank you for your support.

**Comment by taqueci** [comment]
Hi @DolezalDavid 

> How to set Visual Editor for all users as default editor?

There is no way so far.
You can do it by changing source code:
```diff
--- a/assets/javascripts/redmine_wysiwyg_editor.js
+++ b/assets/javascripts/redmine_wysiwyg_editor.js
@@ -197,7 +197,7 @@ RedmineWysiwygEditor.prototype.init = function(editorSetting) {
   self._defaultMode =
     (('localStorage' in window) && (window.localStorage !== null)) ? {
       get: function() {
-        return localStorage.getItem(self._defaultModeKey) || 'text';
+        return localStorage.getItem(self._defaultModeKey) || 'visual'; // Use visual editor for the first time.
       },
       set: function(mode) {
         localStorage.setItem(self._defaultModeKey, mode);
```
or
```diff
--- a/assets/javascripts/redmine_wysiwyg_editor.js
+++ b/assets/javascripts/redmine_wysiwyg_editor.js
@@ -197,7 +197,7 @@ RedmineWysiwygEditor.prototype.init = function(editorSetting) {
   self._defaultMode =
     (('localStorage' in window) && (window.localStorage !== null)) ? {
       get: function() {
-        return localStorage.getItem(self._defaultModeKey) || 'text';
+        return 'visual'; // Always use visual editor as default.
       },
       set: function(mode) {
         localStorage.setItem(self._defaultModeKey, mode);
```

**Comment by DolezalDavid** [comment]
@taqueci thank you! Work nice! 

For me is this task complete so I close it. Thank you guys for your help! :-)
