### ISSUE TITLE
Add watcher

### ISSUE THREAD

**Issue by lcasanova78** [taqueci/redmine_wysiwyg_editor#125]
I am creating a script to be added as a watcher when a user is mentioned with @user, but I am unable to capture the text using javaScript.
Could you give me some hints on how to capture what the user is typing in the editor?

**Comment by taqueci** [comment]
I guess you can capture editor text by:
```js
$(function() {
  $('input[type="submit"]').on('click', function() {
    $(this).closest('form').find('.jstEditor textarea').each(function() {
      var text = $(this).val();

      // Parse text and set watcher here.
    });
  });
});
```
(Some more improvement is needed.)
