### ISSUE TITLE
Do not delete empty row from Textile editor

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#13]
In case of using plugin [Redmine Issue Template](https://github.com/akiko-pusu/redmine_issue_templates), when template has empty row, this row will be removed in Visual editor.

This is Textile:

> %{background: orange;}Result%
> 
> %{background: lightgreen;}Expected%
> 
> Notes:

And Visual editor:

> Result
> Expected
> Notes:

Please leave empty rows in case of Visual editor

Thanks

**Comment by taqueci** [comment]
Hi @chevi 

It's very difficult.

How about putting `&nbsp;`?
```
%{background: orange;}Result%
&nbsp;
%{background: lightgreen;}Expected%
&nbsp;
Notes:
&nbsp;
```

**Comment by chevi** [comment]
Hi @taqueci 
Yeap! `&nbsp;`  do the trick!
Thanks!
