### ISSUE TITLE
User#

### ISSUE THREAD

**Issue by lcasanova78** [taqueci/redmine_wysiwyg_editor#130]
if I have the user#xxxx how can I know his login, I have a redmine instance that if I do User.find_by_id(xxxx) it returns me the user name and not his login, but I need to know his login to send him an email, since his email address is login@email.com.

**Comment by taqueci** [comment]
Hi @lcasanova78 

I guess you can know login name by:
```ruby
User.find_by_id(xxx).login
```
You can also get e-mail address by:
```ruby
User.find_by_id(xxx).mail
```
