### ISSUE TITLE
wysiwig editor for custom fields in Redmine 3.3?

### ISSUE THREAD

**Issue by lcasanova78** [taqueci/redmine_wysiwyg_editor#131]
In Redmine 3.3 there is no Full width layout in custom field setting option, is there any way to use the wysiwyg editor in a custom field?

**Comment by taqueci** [comment]
Hi @lcasanova78 

No, this plugin depends on the full-width layout option.

**Comment by lcasanova78** [comment]
I have tried in Redmine 4.0.1, I have configured a field with Long Text, Text formatting and Full width layout and the editor still does not appear.

**Comment by taqueci** [comment]
Hi @lcasanova78 

This plugin also needs wiki toolbar.
Please use Redmine 4.1.0+.
https://redmine.org/issues/29712

**Comment by taqueci** [comment]
The description has been added to README.
