### ISSUE TITLE
4.2 Compatible?

### ISSUE THREAD

**Issue by vergelli** [taqueci/redmine_wysiwyg_editor#132]
Hello there @taqueci 

**Plataform**: Redmine is Inside a Docker container
**Redmine version**: 4.2.1.stable
**Actual Behavior:** Once installed the plugin and the _Use tabs for mode switch_ box checked => New Issue, and there is no Tab there to change from _Textile_ to _Visual editor_

![1](https://user-images.githubusercontent.com/21988764/132052830-f78936a7-5bb1-4373-bcc2-9006852e7e69.jpg)
![2](https://user-images.githubusercontent.com/21988764/132052833-8a5e5b39-c586-482b-9fd0-61229f5b440a.jpg)

**Expected behavior:**
![3](https://user-images.githubusercontent.com/21988764/132052980-b1057c18-f1c4-44c3-ba3f-f8a111c47551.jpg)

Is this any compatibility issue with Redmine 4.2 build?

# 1 EDIT: 

When I click on Administration => Setting => General. I can see the plugin works for this particular tex block. But only for this one.
![4](https://user-images.githubusercontent.com/21988764/132060408-355be045-57ce-40e0-aae6-0d13195e8bc5.jpg)

**Comment by taqueci** [comment]
@vergelli 

Since version 0.21.0, the visual editor is disabled as default.
Please enable in each project settings.

![](https://user-images.githubusercontent.com/8342349/132077220-b16d5bd3-90db-41c0-9b81-f7efa968040e.png)

**Comment by vergelli** [comment]
@taqueci My bad, everything worked perfectly, thank you.
