### ISSUE TITLE
Wiki name with '  (0x27) Char  Visual editor invalid

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#133]
Wiki name with '  (0x27) Char  Visual editor invalid

**Comment by taqueci** [comment]
Hi @kay54068 

Can you be more specific?

**Comment by kay54068** [comment]
@taqueci 

I update the version "0.22.0" is not   ' (0x27) Char issue ,but the old version v0.20.0 have it , so i close this issue.

thanks.
