### ISSUE TITLE
Upload function targets the first  inputfile of the page

### ISSUE THREAD

**Issue by maudov** [taqueci/redmine_wysiwyg_editor#138]
Hello,

The upload function targets the first file input of the page and may conflict with other plugins.
On our redmine instance we use the redmine_comments plugin (https://github.com/jbbarth/redmine_comments) that adds the ability to write private note and create a new form. We experienced a bug with the redmine_wysiwyg_editor targeting the wrong form.

![image](https://user-images.githubusercontent.com/90309140/150151582-80c6a2a6-c8f5-4b23-8c11-bf11ed4bc13b.png)

We managed to fix this issue, by adding an inputFile property that target the closest form instead of the first input file. 
![image](https://user-images.githubusercontent.com/90309140/150151730-69eaa0a5-2f06-480b-9799-64d15b7c0977.png)

**Comment by mathieu-mbru** [comment]
https://github.com/taqueci/redmine_wysiwyg_editor/pull/140
