### ISSUE TITLE
copy pasting from clipboard with chromium

### ISSUE THREAD

**Issue by maudov** [taqueci/redmine_wysiwyg_editor#139]
Hello,
Copy pasting from clipboard with chromium (95.0.4) does not work.
the DataTransferItemList object does not behave the same way between navigators and the copy paste function is broken.

When using chromium, DataTransferItemList contains 18 elements.
![image](https://user-images.githubusercontent.com/90309140/150154044-3770eb48-7872-4533-993f-090ce877b9a2.png)

and Firefox contains 1 element.
![image](https://user-images.githubusercontent.com/90309140/150154125-1aefbdce-e4c2-4a40-8c84-2e7064b64544.png)

**Comment by mathieu-mbru** [comment]
https://github.com/taqueci/redmine_wysiwyg_editor/pull/140

**Comment by taqueci** [comment]
_This comment is just note to self._

The issue is not reproduced in my environment:
- Ubuntu 21.10
- Google Chrome 97.0.4692.99 (google-chrome-stable/now 97.0.4692.99-1 amd64)

Need more investigation.

![Screenshot from 2022-01-22 10-55-51](https://user-images.githubusercontent.com/8342349/150620618-47cd87b5-8f9a-4e16-af81-928c797dccbc.png)
![Screenshot from 2022-01-22 10-57-37](https://user-images.githubusercontent.com/8342349/150620622-0c54e113-e44b-49ed-b759-9216d092b15c.png)

**Comment by taqueci** [comment]
```
Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-musl]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Mercurial                      5.5.2
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_base_deface            1.5.3
  redmine_comments               0.0.2
  redmine_wysiwyg_editor         0.23.0
```

**Comment by taqueci** [comment]
The issue can not be reproduced on:
- Google Chrome 97.0.4692.99
- Microsoft Edge 97.0.1072.69

**Comment by taqueci** [comment]
Hi @maudov 

Can you please tell me:
- steps to reproduce the issue?
- your Redmine environment (Administration » Information) ?

**Comment by maudov** [comment]
Hi @taqueci,
I wasn't able to reproduce the issue with the last google chrome update (early january).
I had to install an older chrome version to reproduce it.

Since Chrome fixed this I will close this issue.
sorry for the inconvience

**Comment by maudov** [comment]
Hi @taqueci,
There is a similar issue reported on redmine core for older chrome version (https://www.redmine.org/issues/36013).
They fixed the issue on the core so maybe it would make sense to fix it on redmine_wysiwyg. What do you think?

thx

**Comment by taqueci** [comment]
Hi @mathieu-mbru 

Thank you for your pull request!
