### ISSUE TITLE
Improve: add config setting for default height of editor

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#14]
Would be useful to have the configuration for the plugin, where will be possible to set the default height of the editor.
Now this height is 160px only (defined in iframe with id='mce_0_ifr')

**Comment by taqueci** [comment]
Hi @chevi 

Please try one of the solutions below:
* Modify source code
* Use [View Customize plugin](https://github.com/onozaty/redmine-view-customize)

### Modify source code

Add height option to initializer in assets/javascripts/redmine_wysiwyg_editor.js:
```diff
--- a/assets/javascripts/redmine_wysiwyg_editor.js
+++ b/assets/javascripts/redmine_wysiwyg_editor.js
   tinymce.init({
+    height: '320',
     target: self._visualEditor.find('div')[0],
     language: self._language,
     content_style: style,
```

### Use View Customize plugin

Install [View Customize plugin](https://github.com/onozaty/redmine-view-customize) and set script as:
```js
$(function() {
  tinymce.on('AddEditor', function (e) {
    var id = '#' + e.editor.id + '_ifr';

    e.editor.on('init', function (e) {
      $(id).css('height', 320);
    });
  });
});
```

**Comment by chevi** [comment]
Thanks. I'll try solution with Tampermonkey plugin
