### ISSUE TITLE
Upload function targets the first inputfile of the page

### ISSUE THREAD

**Issue by mathieu-mbru** [taqueci/redmine_wysiwyg_editor#144]
Hello,
The upload function targets the first file input of the page and may conflict with other plugins.
On our redmine instance we use the redmine_comments plugin (https://github.com/jbbarth/redmine_comments) that adds the ability to write private note and create a new form. We experienced a bug with the redmine_wysiwyg_editor targeting the wrong form.
![image](https://user-images.githubusercontent.com/75627140/155166396-a7cf4283-d4fa-4a3b-8ef4-e85409f9baa1.png)
We managed to fix this issue, by adding an inputFile property that target the closest form instead of the first input file.
Here is proposition  for this issues.
https://github.com/taqueci/redmine_wysiwyg_editor/pull/143

**Comment by taqueci** [comment]
Hi @mathieu-mbru 

I can't create the environment that Redmine Comments plugin works correctly.
Can you please your Redmine environment information?

**Comment by mathieu-mbru** [comment]
Hello
![Info](https://user-images.githubusercontent.com/75627140/159223553-d713afa3-5cd3-4cb8-ad9d-f64445f27208.PNG)
![plugins](https://user-images.githubusercontent.com/75627140/159223560-08e02804-b782-4f5e-a01b-acb3f0ef2cfd.PNG)
![comments](https://user-images.githubusercontent.com/75627140/159223570-7ba75c1e-2b7e-4b0f-95aa-7f19e9f2927e.gif)

Thankyou

**Comment by mathieu-mbru** [comment]
Hello
we propose another PR (https://github.com/taqueci/redmine_wysiwyg_editor/pull/150)
which is simpler than  (https://github.com/taqueci/redmine_wysiwyg_editor/pull/143)

**Comment by taqueci** [comment]
Hi @mathieu-mbru 

Thank you for your pull request!
