### ISSUE TITLE
Redmine 5

### ISSUE THREAD

**Issue by mmundi72** [taqueci/redmine_wysiwyg_editor#152]
Hi
Redmine 5 has been published and in preperation for a coming update to that new release I have the follwing questions:

- Is the Redmine Wysiwyg Editor already compatible with Redmine 5?
- What about the new CommonMark formatter? Is this already supported? 
- Is it possible to just change the formatter from (Redacarpet) Markdown to CommonMark? What do we have to consider here? (Redcarpet Markdown will be marked deprecated with the release of Redmine 5.1)

**Comment by taqueci** [comment]
> Is the Redmine Wysiwyg Editor already compatible with Redmine 5?
> What about the new CommonMark formatter? Is this already supported?

No, I have not confirmed compatibility yet.

> Is it possible to just change the formatter from (Redacarpet) Markdown to CommonMark? What do we have to consider here? (Redcarpet Markdown will be marked deprecated with the release of Redmine 5.1)

I am going to confirm that now.

**Comment by taqueci** [comment]
Minimal changes for Redmine 5 has been applied.
CommonMark formatting will be considered in issue #153.
