### ISSUE TITLE
I installed the plugin but the application was down

### ISSUE THREAD

**Issue by waysnmeans** [taqueci/redmine_wysiwyg_editor#154]
I installed the plugin but then redmine application was down as soon as restarted after installing the plugin. I am using two copies of Redmine - one is 4.0 and the other is 5.0

Pleas tell me if there is a fix that I need to apply.

**Comment by taqueci** [comment]
Hi @waysnmeans 

Please tell me your Redmine information and the steps to reproduce.

**Comment by taqueci** [comment]
Please reopen if necessary.
