### ISSUE TITLE
Broken table with empty line in editor

### ISSUE THREAD

**Issue by SavchenkoVV** [taqueci/redmine_wysiwyg_editor#156]
Insert table with empty line
![Screenshot_20220727_104055](https://user-images.githubusercontent.com/12197986/181155986-6d8c98f8-2ced-43cc-b525-49fac229c757.png)

Generate source like
![Screenshot_20220727_104118](https://user-images.githubusercontent.com/12197986/181155989-0807c842-8684-49ca-bdd9-4e6920ac162a.png)

Result - broken table
![Screenshot_20220727_104136](https://user-images.githubusercontent.com/12197986/181155990-9d269d54-2b30-495c-8279-81ca885faaf7.png)

**Comment by SavchenkoVV** [comment]
I think it must be
| Header1 | Header2 |
| --- | --- |
|     |     |
|   | Not empty |

**Comment by taqueci** [comment]
This issue may be related to:
https://github.com/mixmark-io/turndown/pull/311

**Comment by taqueci** [comment]
Hi @SavchenkoVV 

Thank you for your reporting the issue.
The issue has been fixed.
