### ISSUE TITLE
Conflict with preview tab on wiki toolbar

### ISSUE THREAD

**Issue by taqueci** [taqueci/redmine_wysiwyg_editor#16]
Preview tab will be implemented in Redmine 4.1.0.
This plugin is significantly affected by the change.
[27758 Adds preview option to the wiki toolbar](http://www.redmine.org/issues/27758)

**Comment by taqueci** [comment]
Note target Redmine version is changed to 4.0.0.

**Comment by taqueci** [comment]
The plugin hides the original toolbar tabs.

**Comment by lauer** [comment]
I have just added #40, with a patch to show the toolbar tabs again if textile editor is selected.
