### ISSUE TITLE
Table header disappears after switching between visual and textile modes

### ISSUE THREAD

**Issue by vomus** [taqueci/redmine_wysiwyg_editor#162]
I created a table in the visual mode and it rightly added `table{width:303px;}.` before the data. But then switching to textile, editing there and switching back into visual, the `table` header disappeared. It seems every time I switch from textile to visual those headers get lost.

**Comment by taqueci** [comment]
Hi @vomus 

This issue is the same as #101 and will be closed.
Please watch #101.
(I don't have enough time to solve this issue...)
