### ISSUE TITLE
Improve: turn on Code Sample plugin

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#17]
Hi

We often use code pasting into redmine issue, but current solution of this plugin displays code formatted text in the same visual way as general text

Could you please add this plugin?
https://www.tiny.cloud/docs/plugins/codesample/

**Comment by taqueci** [comment]
This is just an information for implementing.

| Name        | Redmine 3  | Redmine 4   | Prism      |
|:------------|:-----------|:------------|:-----------|
| C           | c          | c           | c          |
| Clojure     | clojure    | -           | clojure    |
| C++         | cpp        | cpp         | cpp        |
| C#          | -          | csharp      | csharp     |
| CSS         | css        | css         | css        |
| Delphi      | delphi     | -           | -          |
| Diff        | diff       | diff        | diff       |
| ERB         | erb        | -           | erb        |
| Go          | go         | go          | go         |
| Groovy      | groovy     | groovy      | groovy     |
| Haml        | haml       | -           | haml       |
| HTML        | html       | html        | markup     |
| Java        | java       | java        | java       |
| JavaScript  | javascript | javascrript | javascript |
| JSON        | json       | -           | json       |
| Lua         | lua        | -           | lua        |
| Objective C | -          | objc        | objc       |
| Perl        | -          | perl        | perl       |
| PHP         | php        | php         | php        |
| Python      | python     | python      | python     |
| R           | -          | r           | r          |
| Ruby        | ruby       | ruby        | ruby       |
| SASS        | sass       | sass        | sass       |
| Scala       | -          | scala       | scala      |
| Shell       | -          | shell       | bash       |
| SQL         | sql        | sql         | sql        |
| TaskPaper   | taskpaper  | -           | -          |
| Text        | text       | -           | -          |
| XML         | xml        | -           | markup     |
| Swift       | -          | swift       | swift      |
| YAML        | yaml       | yaml        | yaml       |
