### ISSUE TITLE
How to set Chinese

### ISSUE THREAD

**Issue by Dapeng960208** [taqueci/redmine_wysiwyg_editor#170]

**Comment by taqueci** [comment]
Hi @Dapeng960208 

Simplified Chinese is not supported.
I will investigate.

**Comment by taqueci** [comment]
_Note to self_

| Redmine | TinyMCE | Visual Editor |
|--|--|--|
| ar      | ar      | (as-is)       |
| az      | az      | (as-is)       |
| bg      | -       | bg_BG         |
| bs      | -       |               |
| ca      | ca      | (as-is)       |
| cs      | cs      | (as-is)       |
| da      | da      | (as-is)       |
| de      | de      | (as-is)       |
| el      | el      | (as-is)       |
| en-GB   | en_GB   | en_GB         |
| en      | -       |               |
| es-PA   | -       | es            |
| es      | es      | (as-is)       |
| et      | et      | (as-is)       |
| eu      | eu      | (as-is)       |
| fa      | -       | fa_IR         |
| fi      | fi      | (as-is)       |
| fr      | -       |               |
| gl      | gl      | (as-is)       |
| he      | -       | he_IL         |
| hr      | hr      | (as-is)       |
| hu      | -       | hu_HU         |
| id      | id      | (as-is)       |
| it      | it      | (as-is)       |
| ja      | ja      | (as-is)       |
| ko      | -       | ko_KR         |
| lt      | lt      | (as-is)       |
| lv      | lv      | (as-is)       |
| mk      | -       |               |
| mn      | -       |               |
| nl      | nl      | (as-is)       |
| no      | -       |               |
| pl      | pl      | (as-is)       |
| pt-BR   | pt_BR   | pt_BR         |
| pt      | -       | pt_PT         |
| ro      | ro      | (as-is)       |
| ru      | ru      | (as-is)       |
| sk      | sk      | (as-is)       |
| sl      | -       | sl_SI         |
| sq      | -       |               |
| sr-YU   | -       | sr            |
| sr      | sr      | (as-is)       |
| sv      | -       | sv_SE         |
| th      | -       | th_TH         |
| tr      | tr      | (as-is)       |
| uk      | uk      | (as-is)       |
| vi      | -       | vi_VN         |
| zh-TW   | zh_TW   | zh_TW         |
| zh      | -       | zh_CN         |

**Comment by taqueci** [comment]
The issue has been fixed.
Please use version 0.29.0.
