### ISSUE TITLE
The font color picker for Markdown

### ISSUE THREAD

**Issue by pianotako** [taqueci/redmine_wysiwyg_editor#179]
According to Redmine's WIKI - [Markdown formatting](https://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingMarkdown#Color)
It support color text by `HTML tag (<span>)`.

Is it possible to enable color picker for CommonMark Markdown format?

**Comment by taqueci** [comment]
Hi @pianotako 

Color text is supported.
Please use version 0.31.0.

**Comment by pianotako** [comment]
Hi @taqueci, 
Thanks for you help. It work well on Redmine 5.0.
