### ISSUE TITLE
Improve: turn on imagetools_toolbar plugin

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#18]
Hi

Could you please add init of this plugin to have possibility to work with imagetools_toolbar

https://www.tiny.cloud/docs/plugins/imagetools/

Thanks

**Comment by taqueci** [comment]
Hi @chevi 

In develop branch, I have added "Insert image" button and not added image manipulation context menu because it's difficult to implement extra trcik in Redmine as described in [document](https://www.tiny.cloud/docs/plugins/imagetools/).

**Comment by taqueci** [comment]
Please create a new issue if there is a problem.
