### ISSUE TITLE
Rich Text editor is not present for Issues description, comments description, and other textareas.

### ISSUE THREAD

**Issue by salodev** [taqueci/redmine_wysiwyg_editor#180]
I have an redmine 5 installation

I did next steps:

in plugins directory cloned this source code
in root redmine directory `bundle install`
in root redmine directory `passenger-config restart-app`

For projects, once editing an issue, I cant see the rich editor.
In /settings I tried with 'markdown' and 'textile' in Text Format.

Never worked.

But for adding a new project, the description field uses the rich text. But not in other place.

What is my wrong?

**Comment by mmundi72** [comment]
Check in your project if the module "Visual Editor" is enabled (-> Settings of project):

![grafik](https://github.com/taqueci/redmine_wysiwyg_editor/assets/7224922/21bc558c-2a9a-4277-910e-dc8c0475b2d4)

**Comment by taqueci** [comment]
If the issue has not been solved, please reopen.

**Comment by NBA707** [comment]
I installed the plugin in Redmine 5.0.6, the projects editor is the Visual Editor, but Issue editing has the default one.  I am not sure how to get to the Modules list to verify they are all checked.   I pulled up a specific project and went to settings and it's using the default editor and no options to change it.  settings.yml has default: textile should that be changed?
