### ISSUE TITLE
Table with Markdown is broken after previewed and edited.

### ISSUE THREAD

**Issue by two-pack** [taqueci/redmine_wysiwyg_editor#2]
Table with Markdown is broken after previewed and edited, like following:

![capture001](https://user-images.githubusercontent.com/378981/44403942-a3655180-a590-11e8-826b-89eb3701cf22.png)

I have no problem with textile.

**How to reproduce**

1. Set **Markdown** to **Text formatting** on Administration - Settings.
2. Open Wiki on some project, and open new page.
3. Insert Table with visual editor, and input something.
4. Preview it.

**Environment**

```
$ bin/about

sh: darcs: command not found
sh: hg: command not found
sh: cvs: command not found
sh: bzr: command not found
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-darwin16]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               SQLite
SCM:
  Subversion                     1.9.7
  Git                            2.15.2
  Filesystem                     
Redmine plugins:
  redmine_wysiwyg_editor         0.1.0
```

**Comment by taqueci** [comment]
Hi @two-pack san,

I have fixed it.
Could you please try commit 1ee3ae0 in develop branch?

**Comment by two-pack** [comment]
> I have fixed it.
> Could you please try commit 1ee3ae0 in develop branch?

I checked to fix this issue on develop branch.
Thank you for fixing quickly :)

**Comment by taqueci** [comment]
Thank you for checking!
