### ISSUE TITLE
Image doesn't saved if paste it to Edited Note

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#20]
Steps to reproduce:

1. open existed issue with added note
2. ![image](https://user-images.githubusercontent.com/1729590/45949161-914d5780-c003-11e8-8f55-a5881b2ff547.png)
3. Edit Note
4. Paste image there
5. ![image](https://user-images.githubusercontent.com/1729590/45949205-cf4a7b80-c003-11e8-97aa-16ec2ca59cd1.png)
6. Click Save

**Result:**
Image was not uploaded
![image](https://user-images.githubusercontent.com/1729590/45949223-e38e7880-c003-11e8-90f7-28c2d39a04b9.png)

Note: if click Edit on issue and update it, than file will be uploaded. But expeted to upload file by Save Note button

**Comment by taqueci** [comment]
Pasting image is disabled in editing note.

**Comment by chevi** [comment]
Hi @taqueci 
Image pasting doesn't work now, even for new issue description. Can't paste image anywhere.

**Comment by taqueci** [comment]
Hi @chevi 

Thank you for the information.
