### ISSUE TITLE
Image resize doesn't applied

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#23]
**Steps to reproduce:**

1. Paste image to editor
2. resize image by drag and drop of the corner
3. update issue

**Result:**
image is not resized
**Expected:**
saved resized width and height of the image

**Comment by taqueci** [comment]
Hi @chevi 

I have added the functionality.
Please try the latest commit in develop branch.

Note this works only in Textile formatting.

**Comment by taqueci** [comment]
Please create new issue if there is a problem about this functionality.
