### ISSUE TITLE
Editor configuration by external tool

### ISSUE THREAD

**Issue by taqueci** [taqueci/redmine_wysiwyg_editor#24]
Add ability to configure editor by external tool.
e.g. [View customize plugin](https://github.com/onozaty/redmine-view-customize)

**Comment by taqueci** [comment]
Variable `WYSIWYG_EDITOR_CONFIG` is used as TinyMCE editor initialization.

If you want to set editor height with 320px, set View customize plugin setting with:
```js
var WYSIWYG_EDITOR_CONFIG = {
  height: 320
};
```

**Comment by taqueci** [comment]
Variable name is changed from `WYSIWYG_EDITOR_CONFIG` to `WYSIWYG_EDITOR_SETTING`.

If you want to set editor height with 320px, set View customize plugin setting with:
```js
var WYSIWYG_EDITOR_SETTING = {
  height: 320
};
```

**Comment by chevi** [comment]
Hi @taqueci 

I've tried this solution with Tampermonkey Chrome plugin, which do the same as View customize plugin, but have no luck to change height.
Where should this code to be placed? At the start of the page? Or before what element loads I should define this variable?
```
var WYSIWYG_EDITOR_SETTING = {
  height: 320
};
```
My script is:
```
var WYSIWYG_EDITOR_SETTING = {
      height: 720
  };

// next lines to check variable, when editor is loaded
waitForKeyElements("#mce_0_ifr", actionFunction);

function actionFunction(jNode) {
  console.log(WYSIWYG_EDITOR_SETTING);
}
```

Result: 
console:
`{height: 720}`
height is not changed
NOTE: I tried height: "720px" - no luck too

Could you please add a screenshot from the "View customize plugin" with this setting defining?

Thanks!

**Comment by chevi** [comment]
Hi @taqueci 

Tried your script from https://github.com/taqueci/redmine_wysiwyg_editor/issues/25#issuecomment-425889059
and it works on Tampermonkey.
But for still have a trouble how to set WYSIWYG_EDITOR_SETTING variable

**Comment by taqueci** [comment]
Hi @chevi 

Tampermonkey may not set global variable.
I have no idea to solve so far.

Please use View Customize plugin.

Tampermonkey is useful.
I want to consider it when I have time.

**Comment by chevi** [comment]
Hi @taqueci 

Just for note
This is script in Tampermonkey
```
    height: 720,
    plugins: 'link lists hr table textcolor paste',
    paste_as_text: true
};
console.log("just script beginning");
console.log(WYSIWYG_EDITOR_SETTING);

$(function() {
    try {
        tinymce.on('AddEditor', function(e) {
            console.log("added editor");
            console.log(WYSIWYG_EDITOR_SETTING);
            var id = '#' + e.editor.id + '_ifr';

            e.editor.on('init', function(e) {
                var tab = $(id).closest('.wysiwyg-editor').parent().find('.wysiwyg-editor-tab');
                console.log("init editor");
                console.log(WYSIWYG_EDITOR_SETTING);
                tab.find('a[data-type=visual]').trigger('click');
                tab.hide();
            });
        });
    } catch (e) {}
});
```
console output:
![image](https://user-images.githubusercontent.com/1729590/46538012-77d9c480-c8bb-11e8-9b21-2837f97dacca.png)

After page loaded global variable is not accessible
![image](https://user-images.githubusercontent.com/1729590/46538119-cedf9980-c8bb-11e8-9c1b-9b3a3c4d1722.png)


I think that variable is set and accessible in the moment of the editor initiation. Maybe there is a bug?!
