### ISSUE TITLE
Set Visual editor as default view

### ISSUE THREAD

**Issue by jonex2** [taqueci/redmine_wysiwyg_editor#25]
Hi Takeshi!

Is there a possibility to set visual editor as the default view? Please make this as an option.
Then in this case, it would be also good to have another option to hide the links for Textile and Preview.

Thanks!!

**Comment by taqueci** [comment]
Hi @jonex2 

I have no plan to add option so far.

You can do it by using [View Customize plugin](https://github.com/onozaty/redmine-view-customize).
Please try:
1. Install [View Customize plugin](https://github.com/onozaty/redmine-view-customize)
2. Add View Customize plugin setting:
```js
$(function() {
  try {
    tinymce.on('AddEditor', function (e) {
      var id = '#' + e.editor.id + '_ifr';

      e.editor.on('init', function (e) {
        var tab = $(id).closest('.wysiwyg-editor').parent().find('.wysiwyg-editor-tab');

        tab.find('a[data-type=visual]').trigger('click');
        tab.hide();
      });
    });
  } catch(e) {
  }
});
```

**View Customize plugin setting**
![image](https://user-images.githubusercontent.com/8342349/46288278-2631f100-c5c0-11e8-819e-c2781b9f2456.png)

**Comment by jonex2** [comment]
Thank you Takeshi! This works!
