### ISSUE TITLE
Error 500 : Unable to autoload constant RedmineWysiwygEditor

### ISSUE THREAD

**Issue by camlafit** [taqueci/redmine_wysiwyg_editor#31]
Hello

System : Debian stretch/sid  with redmine package 3.4.6-1

After installing plugin and restarted server I get this error : 
```
LoadError (Unable to autoload constant RedmineWysiwygEditor, expected /usr/share/redmine/plugins/redmine_wysiwyg_editor/lib/redmine_wysiwyg_editor.rb to define it):
  plugins/additionals/app/helpers/additionals_menu_helper.rb:110:in `block in addtionals_help_plugin_items'
  plugins/additionals/app/helpers/additionals_menu_helper.rb:104:in `each'
  plugins/additionals/app/helpers/additionals_menu_helper.rb:104:in `addtionals_help_plugin_items'
  plugins/additionals/app/helpers/additionals_menu_helper.rb:139:in `additionals_help_menu_items'
  plugins/additionals/app/helpers/additionals_menu_helper.rb:15:in `additionals_top_menu_setup'
  plugins/additionals/app/views/additionals/_html_head.html.slim:1:in `_0b15245aa2f6a1556415b05e2ae63582'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:17:in `_787ceb9f681de55c5e952923772a7f3d'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by taqueci** [comment]
Hi @camlafit 

I guess the issue is caused by another plugin.

Please tell me:
* Installed plugins
* Plugin versions
* Ruby version
* Rails version

**Comment by camlafit** [comment]
Hello @taqueci 

Thanks for your reply. Then I've on my redmine instance : 
* [Additionals](https://github.com/alphanodes/additionals) 2.0.14
* [Redmine Default Custom Query](https://github.com/hidakatsuya/redmine_default_custom_query) 1.3.0
* [Redmine Git Remote](https://github.com/dergachev/redmine_git_remote) 0.0.1
* [Redmine Spent Time plugin](https://github.com/eyp/redmine_spent_time) 3.1.2
* [ERPmine](http://www.redmine.org/plugins/wk-time) 3.3.4
* [Vault plugin](https://noshutdown.ru/redmine-plugins-vault/) 0.3.7


Redmine 3.4.6.stable
Rails 4.2.10
On Linux pique 3.16.0-4-586 #1 Debian 3.16.43-2+deb8u5 (2017-09-19) i686 GNU/Linux  (was a stretch updated in buster/sid to follow redmine package requirement)

```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [i386-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               SQLite
SCM:
  Subversion                     1.10.3
  Git                            2.19.2
  Filesystem                     
  GitRemote                      2.19.2
Redmine plugins:
  additionals                    2.0.14
  redmine_default_custom_query   1.3.0
  redmine_git_remote             0.0.1
  redmine_spent_time             3.1.2
  redmine_wktime                 3.3.4
  vault                          0.3.7
```

Any problem to disable any plugin or do any other test.

**Comment by taqueci** [comment]
Hi @camlafit 

I have reproduced the error.
Plugin 'Additionals 2.0.14' may be the cause.
Please upgrade it to 2.0.15 or later.

**Comment by camlafit** [comment]
Hello @taqueci  

Thanks a lot, additionnals updated to 2.0.17 and issue is solved :)
