### ISSUE TITLE
copy and paste from excel

### ISSUE THREAD

**Issue by longtian001** [taqueci/redmine_wysiwyg_editor#32]
could not copy and paste from excel table , don't keep the same format in xls file

**Comment by longtian001** [comment]
A | B | C
-- | -- | --
1 | 2 | 3
4 | 5 | 6

**Comment by taqueci** [comment]
Hi @longtian001 ,
Please be more specific about it?

**Comment by taqueci** [comment]
I guess copy and paste is improved by paste plugin implemented by #22.
