### ISSUE TITLE
Doesn't work with Issue Dynamic Edit plugin

### ISSUE THREAD

**Issue by R-Glass** [taqueci/redmine_wysiwyg_editor#33]
The extension (https://github.com/taqueci/redmine_wysiwyg_editor.git) did only work with MS internet-Explorer ...

Chrome, Firefox:
issue-description, issue-comments, wiki were shown as uneditable (grey) with no possibilitiy for input ...

Any help suggestion?

-------------------------------------
__Browser:__ 
* Chrome - Version 70.0.3538.102
* Internet Explorer - 11.0.9600.19236

__Redmine:__
* Environment:
   *   Redmine version                3.4.6.stable
   *   Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
   *  Rails version                  4.2.8
   *   Environment                    production
   *   Database adapter               Mysql2
* SCM:
   *   Subversion                     1.9.5
   *   Git                            2.11.0
   *   Filesystem                     
* Redmine plugins:
   *   a_common_libs                  2.4.9
   *   redmine_agile                  1.4.7
   *   redmine_checklists             3.1.14
   *   redmine_issue_dynamic_edit     0.6.4
   *   redmine_pivot_table            0.0.6
   *   redmine_wiki_extensions        0.8.2
   *   redmineup_tags                 2.0.4
   *   rm_user_mentions               1.0.3

**Comment by taqueci** [comment]
Hi @R-Glass ,

Plugin **redmine_issue_dynamic_edit** may cause the issue.
I guess it's difficult to solve it.

**Comment by skalimer0** [comment]
Yes it's right, the plugin redmine_issue_dynamic_edit is not compatible.

In fact, redmine_issue_dynamic_edit can edit each value directly on the issue (with a simple click ou dlbclick). When we want to edit the description, Visual Editor and the preview is Empty.

The only way to edit the description is to edit the issue (click on "Modify" Button) and edit the description (click on "Edit" link)...

This two plugins are very usefull, and it willl be great to work together.

Can you update the plugin ? or it's to redmine_issue-dynamic_edit to make the job ?

Thanks.
And great job.

**Comment by nanego** [comment]
Hi. Could you please try these changes (here #77) and tell us if it fixes your issue?

Thanks to this update, the Wysiwyg plugin is now compatible with our plugin which loads comments fields through Ajax (https://github.com/jbbarth/redmine_comments)

**Comment by taqueci** [comment]
Pull request #77 has solved the conflict with Issue Dynamic Edit plugin.
Note visual editor mode is not available on editing issue/comment.
