### ISSUE TITLE
Add WYSIWYG function to LongText custom fields

### ISSUE THREAD

**Issue by randylang** [taqueci/redmine_wysiwyg_editor#39]
We would like to be able to use the WYSIWYG function in our custom fields that are formatted Long Text.

**Comment by taqueci** [comment]
Hi @randylang 

It's very difficult to implement by the plugin.

Please wait for Redmine 4.1.
It will be implemented by issue [29712](http://www.redmine.org/issues/29712).

![image](https://user-images.githubusercontent.com/8342349/55634036-98e28a00-57f8-11e9-8c87-ab557eb2cdcb.png)

**Comment by randylang** [comment]
Thank you.
