### ISSUE TITLE
redmine_inline_auto_complete support

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#42]
Hi @taqueci 

hanks for plugin. It is very nice.

What about to support redmine_inline_auto_complete in Visual editor mode?

**Comment by taqueci** [comment]
Hi @kay54068 

It's difficult to support the plugin.

The autocomplete feature is very useful.
I am trying to implement it in branch sandbox/autocomplete-issue, but something wrong... :disappointed:
Please wait patiently.

**Comment by kay54068** [comment]
Hi @taqueci thanks your reply...
Can also support mention user on comment/description using @user with autocomplete ?

ref:
https://www.redmine.org/issues/13919

**Comment by taqueci** [comment]
Hi @kay54068 

I will consider after Redmine 4.1.0 release.

**Comment by taqueci** [comment]
Issue autocomplete has been implemented in version 0.3.6.
Regarding user mention autocomplete, please watch #44.
