### ISSUE TITLE
Insert file function support any format file

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#46]
Hi @taqueci 

I test Insert file function is only support image file , how can support any format in attached files ?

![圖片](https://user-images.githubusercontent.com/3054544/59372824-e50ef500-8d7a-11e9-91d3-dd2b59b769e4.png)

**Comment by taqueci** [comment]
Hi @kay54068 

The latest version supports attachment file link insertion.
