### ISSUE TITLE
Image resize doesn't applied with markdown mode

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#49]
hi @taqueci 

In Textile the image resize it work fine, but in markdown image is not resized.

Textile syntax generate:

`!{height: 413px; width: 734px;}20190616-001310-552.png!`

Markdown syntax generate:

`![](20190616-001838-929.png)`

**Comment by taqueci** [comment]
The issue has been fixed in 0.5.0.

Please note HTML tags need to be allowed.
https://www.redmine.org/boards/2/topics/56096?r=57052#message-57052
