### ISSUE TITLE
How to add customize toolbar function?

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#51]
HI @taqueci,

I installed the plugin for "draw io", this plugin can auto add function to jstoolbar in textile/markdown editor.

How to add a toolbar in Visual Editor (wysiwyg editor)?

ref:

https://github.com/mikitex70/redmine_drawio
https://github.com/mikitex70/redmine_drawio/blob/master/assets/javascripts/drawio_jstoolbar.js

**Comment by taqueci** [comment]
Hi @kay54068 

As mentioned in #48, please see:
https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.editor/#addbutton

I guess you need not only adding button but also a little ingenuity.
