### ISSUE TITLE
 TinyMCE plugin support?

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#53]
How can I support the following  TinyMCE plugins?

Media embed
https://www.tiny.cloud/docs/plugins/mediaembed/

Full screen:
https://www.tiny.cloud/docs/plugins/fullscreen/

**Comment by taqueci** [comment]
Hi @kay54068 

Full screen plugin has been enabled. (#53)

Media plugin needs to be investigated further.

**Comment by kay54068** [comment]
@taqueci 
got it , thanks a lot

**Comment by taqueci** [comment]
I will not enable Media plugin because:
- Difficult to implement
- Few advantages in editing issue/wiki content
