### ISSUE TITLE
collapse support

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#56]
Hi @taqueci
Textile format have collapse macro ,how can I implement it?

collapse macro example:

```
{{collapse(View details...)
This is a block of text that is collapsed by default.
It can be expanded by clicking a link.
}}
```

**Comment by taqueci** [comment]
I had considered macro input method on visual mode, but I have no good idea.

You need to implement:
1. Custom menu and dialog to input macro
2. Convertion to Textile/Markdown
3. Convertion to visual mode content

You can add menu and dialog by:
- https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.editor/#addbutton
- https://www.tiny.cloud/docs-4x/advanced/creating-custom-dialogs/#dialogsashtmlpages

It's difficult to convert Textile/Markdown <-> visual content.
I hope you can make it.
