### ISSUE TITLE
wiki links with alternative name in tables

### ISSUE THREAD

**Issue by MichaelLorenzen** [taqueci/redmine_wysiwyg_editor#59]
Hi,

if i use wiki links with alternative names like `[[wikipage|link name]]` inside a table the |-symbol is interpreted as the end of the table cell. The `link name` is written into the next cell an the table in this row is longer in the visual editor.

Example:
    

| A1 | B1 | C1 |
    | A2 | [[Wiki|Link in B2]] | C2 |
    | A3 | B3 | C3 |

is rendered as:
![Screenshot_2019-08-09 Wiki - Test_WYSIWYG](https://user-images.githubusercontent.com/6518669/62777464-e5431c80-baad-11e9-916c-75a82664e6da.png)

**Comment by taqueci** [comment]
Hi @MichaelLorenzen 

This is known issue with Redmine:
https://www.redmine.org/issues/23341

Please wait for it to be fixed.

**Comment by MichaelLorenzen** [comment]
Hi @taqueci ,

this is not an issue in redmine 4.0.4 (which I am using) any more (not in preview and not after saving the page):
![Screenshot_2019-08-13 Wiki - Test_WYSIWYG - Redmine(2)](https://user-images.githubusercontent.com/6518669/62933246-0cf1f780-bdc2-11e9-8f80-ce305241df84.png)

But it is not rendered correct while in wysiwyg-editor:
![Screenshot_2019-08-13 Wiki - Test_WYSIWYG - Redmine(1)](https://user-images.githubusercontent.com/6518669/62933317-39a60f00-bdc2-11e9-92a1-25aae219df6e.png)

**Comment by taqueci** [comment]
Hi @MichaelLorenzen 

Thank you for your explanation.
I  will try to solve the issue.

**Comment by taqueci** [comment]
The issue has been fixed.
