### ISSUE TITLE
Plugin not workin on Redmine 4.0.4-3

### ISSUE THREAD

**Issue by jogibear9988** [taqueci/redmine_wysiwyg_editor#60]
I've the following error in my log:

	Creating scope :system. Overwriting existing method Enumeration.system.
	Creating scope :sorted. Overwriting existing method User.sorted.
	Creating scope :sorted. Overwriting existing method Group.sorted.
	Creating scope :visible. Overwriting existing method AgileQuery.visible.
	Creating scope :visible. Overwriting existing method PeopleQuery.visible.
	Creating scope :system. Overwriting existing method Enumeration.system.
	Creating scope :sorted. Overwriting existing method User.sorted.
	Creating scope :sorted. Overwriting existing method Group.sorted.
	Creating scope :visible. Overwriting existing method AgileQuery.visible.
	Creating scope :visible. Overwriting existing method PeopleQuery.visible.
	Started GET "/redmine/" for 127.0.0.1 at 2019-08-15 13:30:02 +0200
	Processing by WelcomeController#index as HTML
	  Current user: jkuehner (id=7)
	  Rendering welcome/index.html.erb within layouts/base
	  Rendered welcome/index.html.erb within layouts/base (96.6ms)
	Missing template, responding with 404: Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"

	  Rendering common/error.html.erb within layouts/base
	  Rendered common/error.html.erb within layouts/base (0.7ms)
	Completed 500 Internal Server Error in 1120ms (ActiveRecord: 179.4ms)
	  
	ActionView::Template::Error (Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"
	):
		13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
		14: <%= javascript_heads %>
		15: <%= heads_for_theme %>
		16: <%= call_hook :view_layouts_base_html_head %>
		17: 
		18: <%= yield :header_tags -%>
		19: </head>
	  
	lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
	lib/redmine/hook/view_listener.rb:57:in `map'
	lib/redmine/hook/view_listener.rb:57:in `block in render_on'
	lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
	lib/redmine/hook.rb:61:in `each'
	lib/redmine/hook.rb:61:in `block in call_hook'
	lib/redmine/hook.rb:58:in `tap'
	lib/redmine/hook.rb:58:in `call_hook'
	lib/redmine/hook.rb:96:in `call_hook'
	app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__1006469287_95666000'
	app/controllers/application_controller.rb:499:in `block (2 levels) in render_error'
	app/controllers/application_controller.rb:497:in `render_error'
	app/controllers/application_controller.rb:485:in `render_404'
	app/controllers/application_controller.rb:509:in `missing_template'
	Started GET "/redmine/" for 127.0.0.1 at 2019-08-15 13:30:54 +0200
	Processing by WelcomeController#index as HTML
	  Current user: jkuehner (id=7)
	  Rendering welcome/index.html.erb within layouts/base
	  Rendered welcome/index.html.erb within layouts/base (3.6ms)
	Missing template, responding with 404: Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"

	  Rendering common/error.html.erb within layouts/base
	  Rendered common/error.html.erb within layouts/base (0.1ms)
	Completed 500 Internal Server Error in 251ms (ActiveRecord: 5.7ms)
	  
	ActionView::Template::Error (Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"
	):
		13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
		14: <%= javascript_heads %>
		15: <%= heads_for_theme %>
		16: <%= call_hook :view_layouts_base_html_head %>
		17: 
		18: <%= yield :header_tags -%>
		19: </head>
	  
	lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
	lib/redmine/hook/view_listener.rb:57:in `map'
	lib/redmine/hook/view_listener.rb:57:in `block in render_on'
	lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
	lib/redmine/hook.rb:61:in `each'
	lib/redmine/hook.rb:61:in `block in call_hook'
	lib/redmine/hook.rb:58:in `tap'
	lib/redmine/hook.rb:58:in `call_hook'
	lib/redmine/hook.rb:96:in `call_hook'
	app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__1006469287_95666000'
	app/controllers/application_controller.rb:499:in `block (2 levels) in render_error'
	app/controllers/application_controller.rb:497:in `render_error'
	app/controllers/application_controller.rb:485:in `render_404'
	app/controllers/application_controller.rb:509:in `missing_template'
	Started GET "/redmine/" for 127.0.0.1 at 2019-08-15 13:30:55 +0200
	Processing by WelcomeController#index as HTML
	  Current user: jkuehner (id=7)
	  Rendering welcome/index.html.erb within layouts/base
	  Rendered welcome/index.html.erb within layouts/base (118.5ms)
	Missing template, responding with 404: Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"

	  Rendering common/error.html.erb within layouts/base
	  Rendered common/error.html.erb within layouts/base (0.6ms)
	Completed 500 Internal Server Error in 980ms (ActiveRecord: 99.2ms)
	  
	ActionView::Template::Error (Missing partial redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmineup_tags/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_people/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_checklists/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/redmine_agile/app/views"
	  * "C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/app/views"
	):
		13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
		14: <%= javascript_heads %>
		15: <%= heads_for_theme %>
		16: <%= call_hook :view_layouts_base_html_head %>
		17: 
		18: <%= yield :header_tags -%>
		19: </head>
	  
	lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
	lib/redmine/hook/view_listener.rb:57:in `map'
	lib/redmine/hook/view_listener.rb:57:in `block in render_on'
	lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
	lib/redmine/hook.rb:61:in `each'
	lib/redmine/hook.rb:61:in `block in call_hook'
	lib/redmine/hook.rb:58:in `tap'
	lib/redmine/hook.rb:58:in `call_hook'
	lib/redmine/hook.rb:96:in `call_hook'
	app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__903508043_95656240'
	app/controllers/application_controller.rb:499:in `block (2 levels) in render_error'
	app/controllers/application_controller.rb:497:in `render_error'
	app/controllers/application_controller.rb:485:in `render_404'
	app/controllers/application_controller.rb:509:in `missing_template'

Used Plugins:

redmine_agile
redmine_checklists
redmine_people
redmineup_tags

**Comment by taqueci** [comment]
Note to self:
It works on Ubuntu 19.04.
```
Environment:
  Redmine version                4.0.4.stable.18371
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    development
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.0
  Mercurial                      4.8.2
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.12
  redmine_checklists             3.1.16
  redmine_people                 1.4.1
  redmine_wysiwyg_editor         0.6.0
  redmineup_tags                 2.0.8
```

**Comment by taqueci** [comment]
Note to self:
On Bitnami, the issue is caused by Redmine Agile plugin.
```
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x64-mingw32]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.16
  redmine_people                 1.4.1
  redmine_wysiwyg_editor         0.6.0
  redmineup_tags                 2.0.8
```
![image](https://user-images.githubusercontent.com/8342349/63159743-2d86af80-c057-11e9-97b5-4382a1e9d45a.png)

**Comment by taqueci** [comment]
Hi @jogibear9988 

Bitnami Redmine does not work with Redmine Agile plugin.
My plugin has nothing to do with the issue.

Please ask the developer of Redmine Agile plugin.

**Comment by jogibear9988** [comment]
But we have "Redmine" running without your Plugin and use the Agile Plugin and it works.
If we add your's it fails

**Comment by taqueci** [comment]
Hi @jogibear9988 

Please tell me plugin versions and edtion (light or PRO).

**Comment by jogibear9988** [comment]
Redmine Agile plugin (Light version) 1.4.12
Redmine Checklists plugin (Light version) 3.1.16
Redmine People plugin (Light version) 1.4.1
Redmine Tags plugin (Light version) 2.0.7

**Comment by jogibear9988** [comment]
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x64-mingw32]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.12
  redmine_checklists             3.1.16
  redmine_people                 1.4.1
  redmineup_tags                 2.0.7

**Comment by jogibear9988** [comment]
@taqueci could you detect any issue?

**Comment by jogibear9988** [comment]
don't know what I've changed...
I've tryed again now with a clean git checkout and it works... 

thanks for your help
