### ISSUE TITLE
Image Upload by File Picker

### ISSUE THREAD

**Issue by jogibear9988** [taqueci/redmine_wysiwyg_editor#63]
Would it be possible to allow this also?

See:
https://www.tiny.cloud/docs/demo/file-picker/
https://www.tiny.cloud/docs/configure/file-image-upload/

**Comment by taqueci** [comment]
Drag and drop is not enabled because of technical issue.
It will take a long time to solve it.

This issue is controlled by the issue #64.

**Comment by jogibear9988** [comment]
what is the tecnical issue? maybe I could help?

and what about the file picker upload?

Von meinem iPhone gesendet

**Comment by taqueci** [comment]
Hi @jogibear9988 

Your pull request is welcome!

It's easy to support drag and drop with one file.
In case of two or more files, a little bit of trick may be needed.

Regarding to file picker, it looks good.

**Comment by taqueci** [comment]
Image drag and drop feature has been implemented in 0.8.0.
This issue is closed.
