### ISSUE TITLE
Does not work with receive emails

### ISSUE THREAD

**Issue by mpauz** [taqueci/redmine_wysiwyg_editor#65]
There is possibility to replace <tr> <td> tags to "|" to create normal table from email, or do not split into new lines?

**Comment by taqueci** [comment]
Hi @mpauz 

Please tell me more in detail.

**Comment by taqueci** [comment]
Hi @mpauz 

Please note table border is not shown in notification mail if your Redmine is 3.3 or earlier.
http://www.redmine.org/issues/25842

**Comment by taqueci** [comment]
Hi @mpauz 

I close this issue.
If you use Redmine 3.4+, please reopen and tell me more detail.
