### ISSUE TITLE
Improvement: paste images

### ISSUE THREAD

**Issue by chevi** [taqueci/redmine_wysiwyg_editor#7]
Please make an improvement that will paste image from clipboard into the text directly

Thanks

**Comment by taqueci** [comment]
I guess it's not so easy.
I will investigate the feasibility.

**Comment by taqueci** [comment]
Hi @chevi,

The image pasting functionality has been implemented.
Please try the latest version.

It works in Firefox and Chrome.
I will not support the other browser because of technical reasons.

**Comment by chevi** [comment]
Hi @taqueci 

Unfortunately attachment files doesn't found after paste image

![screenshot at 11-25-39](https://user-images.githubusercontent.com/1729590/45412163-ad094300-b67e-11e8-9a7f-480d34672569.png)

**Comment by taqueci** [comment]
Hi @chevi 

Please tell me:
* Redmine version
* Installed plugins
* Browser version
* Condition (e.g. anonymous user)

**Comment by chevi** [comment]
Hi @taqueci 
Might be it's because of Clipboard image paste plugin, which we are using currently?! Or something else.. Thanks!

**Redmine version**
- Redmine 3.3.0.stable

**Installed plugins**
- - Time Logger
- - Redmine Work Time plugin
- - Redmine Theme Changer plugin
- - Redmine Issue Templates plugin
- - Redmine Embedded Video
- - Clipboard image paste
- - A common libraries
- - Extra Queries plugin

**Browser version**
- Chrome 68 / Firefox 62 (64-bit) / Vivaldi 1.15.1147.64 (64-bit)

**Condition (e.g. anonymous user)**
- Logged in as admin user

**Comment by taqueci** [comment]
Hi @chevi 

I have confirmed it does not work in Redmine 3.3.
I will fix it.
