### ISSUE TITLE
Degree ° get's replaced by (o)

### ISSUE THREAD

**Issue by FLeischsalatus** [taqueci/redmine_wysiwyg_editor#70]
The ° character, when entered in the Visual Editor, will be replaced by (o) when the text gets transformed to Textile.

**Comment by FLeischsalatus** [comment]
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.22-master
  clipboard_image_paste          1.13
  redmine_checklists             3.1.16
  redmine_db                     2.0.4
  redmine_kwk_modifications      1.2.5
  redmine_lightbox2              0.5.0
  redmine_local_avatars          0.2.0
  redmine_passwords              2.0.4
  redmine_privacy_terms          1.0.2
  redmine_reporting              2.0.4
  redmine_wiki_lists             0.0.9
  redmine_wysiwyg_editor         0.6.0
  sidebar_hide                   0.0.8-fix

**Comment by taqueci** [comment]
Hi @FLeischsalatus 

Thank you for your reporting.
I have confirmed the issue.
I will try to solve it.

**Comment by taqueci** [comment]
The issue has been fixed.

**Comment by FLeischsalatus** [comment]
Great! Thanks a lot!
Awesome plugin btw 👍
