### ISSUE TITLE
Bug with text on the table.

### ISSUE THREAD

**Issue by Berendor** [taqueci/redmine_wysiwyg_editor#73]
Hi, @taqueci  thanks for the great plugin.

A bug related to tables was detected. If you try to create a list in the table (unnumbered and numbered), then after saving the cells in which the list was disappear.

**input**
![Снимок экрана от 2019-10-30 16-26-45](https://user-images.githubusercontent.com/51061935/67862645-87b1ef80-fb33-11e9-8c5e-3895330b66d4.png)

**output**
![Снимок экрана от 2019-10-30 16-27-03](https://user-images.githubusercontent.com/51061935/67862658-8da7d080-fb33-11e9-9698-d5207cd3e333.png)

And even after saving the table, styles disappear in it and the transferred text merges into one line.

**input**
![Снимок экрана от 2019-10-30 16-35-42](https://user-images.githubusercontent.com/51061935/67862880-f4c58500-fb33-11e9-9792-9b96afa90741.png)

**output**
![Снимок экрана от 2019-10-30 16-35-59](https://user-images.githubusercontent.com/51061935/67862892-fa22cf80-fb33-11e9-8b10-3351bafb73b0.png)

**Comment by taqueci** [comment]
Hi @Berendor 

Thank you for your reporting.
In table, numbered/bulleted list should be disabled because Textile/Markdown does not support.
I will try to improve UI.

**Comment by taqueci** [comment]
_Note to self_

In table, the following controls should be disabled:
* Format
* Code sample
* Numbered list
* Bulleted list
* Blockquote
* Horizontal rule
* Table insertion

**Comment by taqueci** [comment]
Table insertion should also be disabled, but it has not been done yet.
