### ISSUE TITLE
Bug with attachments

### ISSUE THREAD

**Issue by Berendor** [taqueci/redmine_wysiwyg_editor#74]
Hello
If there is a problem with attachments, if you put more than one space between the text and attachment, then characters are inserted that break the link
![image](https://user-images.githubusercontent.com/51061935/68213161-17e8ac80-ffec-11e9-8039-63cd4e718230.png)
![image](https://user-images.githubusercontent.com/51061935/68213191-25059b80-ffec-11e9-8a1a-216459df624f.png)
![image](https://user-images.githubusercontent.com/51061935/68213260-46ff1e00-ffec-11e9-85ba-380360a44905.png)

**Comment by taqueci** [comment]
Hi @Berendor 

Thank you for your reporting.
The issue has been confirmed on Chrome.
I will try to solve.

**Comment by taqueci** [comment]
_Note to self:_
**Chrome**

| Input                     | HTML                       |
| :------------------------ | :------------------------- |
| `"foo"`                   | `"foo"`                    |
| `"foo "` (1 space)        | `"foo&nbsp;"`              |
| `"foo bar"` (1 space)     | `"xfoo bar"`               |
| `"foo  "` (2 spaces)      | `"foo&nbsp;&nbsp;"`        |
| `"foo  bar"` (2 spaces)   | `"foo&nbsp; bar"`          |
| `"foo   "` (3 spaces)     | `"foo&nbsp; &nbsp;"`       |
| `"foo   bar"` (3 spaces)  | `"foo&nbsp; &nbsp;bar"`    |
| `"foo    "` (4 spaces)    | `"foo&nbsp; &nbsp;&nbsp;"` |
| `"foo    bar"` (4 spaces) | `"foo&nbsp; &nbsp; bar"`   |

**Comment by taqueci** [comment]
_Note to self:_

| Input               | Firefox                   | Chrome                  |
|:--------------------|:--------------------------|:------------------------|
| `a b` (1 space)     | `61 20 62`                | `61 20 62`              |
| `a  b` (2 spaces)   | `61 c2a0 20 62`           | `61 c2a0 20 62`         |
| `a   b` (3 spaces)  | `61 c2a0 c2a0 20 62`      | `61 c2a0 20 c2a0 62`    |
| `a    b` (4 spaces) | `61 c2a0 c2a0 c2a0 20 62` | `61 c2a0 20 c2a0 20 62` |

**Comment by taqueci** [comment]
The issue has been fixed.
