### ISSUE TITLE
Preview tab is not shown on toolbar of Redmine 4.0

### ISSUE THREAD

**Issue by kimuraos** [taqueci/redmine_wysiwyg_editor#78]
Redmine 4.0 introduced preview tab on toolbar:
https://www.redmine.org/issues/27758

After installing this plugin, the preview tab would not be appeared.
I think "preview" link at bottom of textarea conflicts with the preview tab.

**Comment by taqueci** [comment]
Hello @kimuraos san,

The plugin hides preview tab for compatibility with Redmine 3.
Please use "preview" link.
