### ISSUE TITLE
Spellchecking

### ISSUE THREAD

**Issue by Daeloran** [taqueci/redmine_wysiwyg_editor#80]
Hello,

Is it possible to add spellchecking functionnality for the WYSIWYG mode ?
Or maybe it's already here but in this case it doesn't work on redmine 4.0 for me.

Thank you

Nicolas

**Comment by taqueci** [comment]
Hi @Daeloran ,

Thank you for your suggestion.
I will consider it.

You can enbale by adding `browser_spellcheck: true` to initialization parameter:
```diff
--- a/assets/javascripts/redmine_wysiwyg_editor.js
+++ b/assets/javascripts/redmine_wysiwyg_editor.js
@@ -399,6 +399,7 @@ RedmineWysiwygEditor.prototype._initTinymce = function(setting) {
 
   tinymce.init($.extend({
     // Configurable parameters
+    browser_spellcheck: true,
     language: self._language,
```

**Comment by taqueci** [comment]
https://www.tiny.cloud/docs-4x/configure/spelling/#browser_spellcheck

**Comment by taqueci** [comment]
Spell checker has been enabled.
