### ISSUE TITLE
which tag support 3.2.6

### ISSUE THREAD

**Issue by Quenii** [taqueci/redmine_wysiwyg_editor#81]
I'm using redmine 3.2.6 stable, so which version should i try?
the latest version **do not** work

**Comment by taqueci** [comment]
Hi @Quenii 

I have confirmed the latest version 0.14.0 works with Redmine 3.2.6.
[Dockerfile.zip](https://github.com/taqueci/redmine_wysiwyg_editor/files/4192894/Dockerfile.zip)

Please check installed plugins.

**Comment by Quenii** [comment]
sorry for late response. 
I've almost every tag, all got error message showed below
and the err log don't show any useful info.

i've followed the readme to download and decompress.
should I do more install operation?


Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

**Comment by Quenii** [comment]
sorry to bother, 
i think i find the issue. 

If I don't solve it, i'll post again

thanks for beautiful work

**Comment by taqueci** [comment]
Hi @Quenii 

> i've followed the readme to download and decompress.
> should I do more install operation?

No, all you have to do is to decompress and to restart Redmine.

Please tell me other installed plugins.
