### ISSUE TITLE
Preview is not working with Redmine Mentions plugin

### ISSUE THREAD

**Issue by Jamalc0m** [taqueci/redmine_wysiwyg_editor#82]
When editing or adding new ticket, preview option is not working

**Comment by Jamalc0m** [comment]
@taqueci

**Comment by taqueci** [comment]
Hi @Jamalc0m 

Please tell me:

- Steps to reproduce
- Redmine version
- Installed plugins
- Plugin versions
- Browser version
- Console messages of development tool

**Comment by Jamalc0m** [comment]
Create new ticket

Type your description

![image](https://user-images.githubusercontent.com/8554119/74406842-bda88480-4e41-11ea-861c-f95d27746c18.png)

Click preview

![image](https://user-images.githubusercontent.com/8554119/74406890-d749cc00-4e41-11ea-8b7f-2eeaa3f5a5ba.png)

Nothing There!

Browser Chrome - Firefox

**Installed plugins & Versions:**

![image](https://user-images.githubusercontent.com/8554119/74407124-5b03b880-4e42-11ea-8f4b-089a8a5fc9c6.png)

**Console messages of development tool**
No error reported!

![image](https://user-images.githubusercontent.com/8554119/74407177-7f5f9500-4e42-11ea-9894-2596fe6e706b.png)

**Note:**
Normal editor which comes with redmine working fine with no issue.

**Comment by taqueci** [comment]
_Note to self:_
The plugin conflicts with Redmine Mentions plugin.
[Dockerfile.zip](https://github.com/taqueci/redmine_wysiwyg_editor/files/4199250/Dockerfile.zip)

**Comment by Jamalc0m** [comment]
any work around to fix ?

**Comment by etoosamoe** [comment]
same problem. we have Mentions plugin installed and preview is not working.
Any fix?

**Comment by etoosamoe** [comment]
This trouble appears only in Issue editing\creating. May be there is any option to disable wysiwig in issues, only wiki?

**Comment by taqueci** [comment]
Hi @etoosamoe 

You can hide visual editor in issue creating/editing by:
```diff
--- a/app/views/redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial.html.erb
+++ b/app/views/redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial.html.erb
@@ -52,6 +52,12 @@ function initRedmineWysiwygEditor() {
     $('.jstTabs, .jstElements, .jstEditor').css('visibility', 'visible');
   };
 
+  if (<%= @issue ? 'true' : 'false' %>) {
+    setVisible();
+    $('#content .jstBlock .jstTabs ul li:not(.tab-elements)').show();
+    return;
+  }
+
   var previewTab = $('.jstTabs .tab-preview');
   var previewButton = $('a[accesskey=r]');
```

**Comment by etoosamoe** [comment]
@taqueci thanks! it works. wysiwyg editor now disabled in issues, but works fine (with preview) in Wiki.
nice workaround

**Comment by varenius** [comment]
I also have this problem. It would be nice to have the editor working also with preview in issues. Is there any plan to fix this incompatibility?

**Comment by epomorski** [comment]
Joining a request to solve this issue.

**Comment by taqueci** [comment]
I hope the issue is fixed.
