### ISSUE TITLE
Dynamic edit Issue plugin - don't work when I editing issue, only work when I create a new issue

### ISSUE THREAD

**Issue by duc-it** [taqueci/redmine_wysiwyg_editor#89]

**Comment by taqueci** [comment]
Hi @duc-it 

Please tell me your Redmine information and the steps to reproduce.

**Comment by duc-it** [comment]
COMPONENTS

Bitnami Redmine Stack ships with the following software versions:

  - Redmine 4.1.0
  - Apache 2.4.41
  - ImageMagick 6.9.8
  - MySQL 5.7.28
  - Subversion 1.13.0
  - Git 2.19.1
  - Ruby 2.5.7
  - Rails 5.0.7.2
  - RubyGems 2.7.9

Plugins recents:

![image](https://user-images.githubusercontent.com/67086464/85089261-601bae80-b20c-11ea-9d8e-ed95e05ffb2c.png)

**Comment by taqueci** [comment]
Hi @duc-it 

Thank you for the information.
Could you please tell me plugin versions?
(Administration » Information)

**Comment by duc-it** [comment]
![image](https://user-images.githubusercontent.com/67086464/85106542-8fdfac00-b236-11ea-9495-21ade86ab625.png)
 thank you quick responded!

**Comment by taqueci** [comment]
Thank you, @duc-it 

I have confirmed redmine_issue_dynamic_edit causes the issue.
I will investigate more, but it may be difficult to solve.
Please don't get your hopes up.

**Comment by duc-it** [comment]
Thank you very much, @taqueci

**Comment by veggie4ever** [comment]
Hi @taqueci,
do you have any news on this issue? I'm having the same problem with this setup:

Environment:
  Redmine version                4.1.6.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.6.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.24
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_issue_dynamic_edit     0.8.1
  redmine_remote_revision_url    0.3.2
  redmine_wysiwyg_editor         0.26.0

**Comment by taqueci** [comment]
> do you have any news on this issue?

No, I have no idea to solve the issue...

**Comment by pr-dtakac** [comment]
Hi, we have the same problem - no visual editor tab (unable use visual editor) when editing issue, tab is visible only when creating issue. Any idea what can be wrong? Thanks a lot..

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.4
  redmine_checklists             3.1.18
  redmine_contacts               4.3.2
  redmine_contacts_helpdesk      4.1.11
  redmine_custom_css             0.1.7
  redmine_default_assign         0.6
  redmine_improved_searchbox     0.0.3
  redmine_issues_tree            0.0.14
  redmine_people                 1.6.0
  redmine_questions              1.0.2
  redmine_reporter               1.0.3
  redmine_resources              1.0.4
  redmine_wysiwyg_editor         0.27.1
  redmine_zenedit                2.0.0
  redmineup_tags                 2.0.8

**Comment by pr-dtakac** [comment]
Previous post was about environment without redmine_issue_dynamic_edit plugin.
On another environment with this plugin we had the same problem as described. Finally I found the bug in that plugin and after my changes it's working fine.
See my fix: https://github.com/Ilogeek/redmine_issue_dynamic_edit/issues/98#issuecomment-1333613453

**Comment by taqueci** [comment]
I have confirmed it works with Issue Dynamic Edit plugin.
(There might be another issue about input form position.)
 ```
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux-musl]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.2
  Mercurial                      6.1.1
  Bazaar                         3.2.1
  Git                            2.36.3
  Filesystem                     
Redmine plugins:
  redmine_issue_dynamic_edit     0.9.1
  redmine_wysiwyg_editor         0.28.0
```
