### ISSUE TITLE
ENH: Optional switching off of Visual Editor mode 

### ISSUE THREAD

**Issue by dinya** [taqueci/redmine_wysiwyg_editor#91]
For discuss.

Because of some problems with the conversion "Visual editor" < - > "Markdown" ("Texitle"?) in both directions now (see, for example, #90) and perhaps in the future, I think it will be useful to add the "Don't use Visual editor" option to each Formatted text row (the default behavior is in the plugin settings in the Redmine admin panel).

Thus, this option will allow you to keep the old formatted text undamaged when bugs are reported and for the fixing period.

Moreover the plugin will be production-ready. What do I mean? The plugin is already ready for 90% of usage cases. But it's cool when you don't think about rendering result every time you edit the complex text (just set the option and edit in the "raw" mode).

**Comment by dpalic** [comment]
+1

would suggest also a full enable/disable flag on plugin settings page, so it can stay installed but will be disabled totally if some issue occurs.

the above named feature could push the plugin to production even faster

**Comment by taqueci** [comment]
Added ability to enable/disable the visual editor per project.
