### ISSUE TITLE
Add styling possibilties to tables

### ISSUE THREAD

**Issue by mmundi72** [taqueci/redmine_wysiwyg_editor#93]
Is it possible that you active the standard TinyMCE features of styling the tables. Especially helpful are the following settings (Screenshot from the TinyMCE-Website):

![grafik](https://user-images.githubusercontent.com/7224922/85672109-d6b02480-b6c2-11ea-83f0-e2bc67ff9e09.png)

**Comment by taqueci** [comment]
Hi @mmundi72 

Border style/color and background color are not available because these properties are not allowed in both Textile and Markdown.
