### ISSUE TITLE
Feature Request: Use tabs to switch between modes

### ISSUE THREAD

**Issue by mmundi72** [taqueci/redmine_wysiwyg_editor#95]
It would be great to place the current links Textile, Visual Editor, Preview above the editor using the newly introduced tabs in issues. This suits better with the rest of Redmine.

These links:
![image](https://user-images.githubusercontent.com/7224922/86537285-5bcee100-beee-11ea-9487-6737725c5eb4.png)

Place them above editor similar to the issues history tabs:
![image](https://user-images.githubusercontent.com/7224922/86537347-bf590e80-beee-11ea-8e1d-8f9b3e985290.png)

**Comment by picman** [comment]
Yes, the **Visual editor** should be integrated into the existing tabs between **Edit** and **Preview**. The present solution with links below the edit control is ugly.
![image](https://user-images.githubusercontent.com/779003/107616767-f9da1500-6c4e-11eb-948b-0a2a4a5edd40.png)

**Comment by albrechtd** [comment]
Furthermore, it would be great if the preview background would be white instead of light gray, as this confuses some of my users (“Why does the result look _so_ different from the preview?”).  It can be tweaked easily be changing the value `#fafafa` to `#ffffff` in the stylesheet css, but it's overwritten by updates…

**Comment by albrechtd** [comment]
After a lot of trial-and-error (and error and error and error 😉) on Redmine 4.0.7 installed from Buster Backports, I *think* I found a solution using this patch against version 0.20.0.
[redmine_wysiwyg_editor-with-tabs.zip](https://github.com/taqueci/redmine_wysiwyg_editor/files/6018204/redmine_wysiwyg_editor-with-tabs.zip)
At least, using Firefox it now looks as the familiar Redmine interface, just with the additional tab.  However, I have **no** idea if it works with other browsers or with other versions of Redmine, degrades your Karma or has other evil side effects.  But it *might* be a starting point.
![hack-textile](https://user-images.githubusercontent.com/22217289/108633774-6b4b6c00-7476-11eb-8317-96fb5f4a46a8.png)
![hack-wysiwyg](https://user-images.githubusercontent.com/22217289/108633780-71d9e380-7476-11eb-8ce3-8203329c5324.png)

**Comment by picman** [comment]
Excellent! I've tested it with the current develop branch and can confirm that it simply works. I've fixed a problem that the main view is scrolling when clicking on tabs and created a pull request https://github.com/taqueci/redmine_wysiwyg_editor/pull/116 for easier integration.

**Comment by taqueci** [comment]
Merged.

**Comment by taqueci** [comment]
Please enable `Use tabs for mode switch` in plugin setting.

**Comment by picman** [comment]
So, reopen the issue and assign it to me.
