### ISSUE TITLE
Display Font Awesome Icons in Editor Mode

### ISSUE THREAD

**Issue by FLeischsalatus** [taqueci/redmine_wysiwyg_editor#98]
I would love to see the Font Awesome Icons in Visual Editor Mode.

Right now, it looks like this:

**Editor Mode**

![grafik](https://user-images.githubusercontent.com/56909015/87509451-dd064080-c671-11ea-9a6b-698fe4c2e483.png)

**Preview** 

![grafik](https://user-images.githubusercontent.com/56909015/87509472-e8f20280-c671-11ea-8087-a4e1cfa4bc73.png)

**Comment by taqueci** [comment]
Thank you for your suggestion.
I love Font Awesome, too.
However, I don't support macros extended by another plugin.
