### ISSUE TITLE
Add Awesome Icons from Toolbar

### ISSUE THREAD

**Issue by FLeischsalatus** [taqueci/redmine_wysiwyg_editor#99]
Please add a Macro Button to choose and add an Icon from the Font Awesome Catalogue.

**Design**

![grafik](https://user-images.githubusercontent.com/56909015/87511270-54899f00-c675-11ea-985d-0d79bb95a028.png)

**Textile Code**

{{fa(bug,color=green,size=2x)}}

**Comment by taqueci** [comment]
Thank you for your suggestion.
For the same reason as #98, I don't support macros extended by another plugin.
